/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package behavioranalyst;

import NDL_JavaClassLib.MultiSelectFrame;



/**
 *
 * @author Balaji
 */
public class FrontEnd_MainFrame extends javax.swing.JFrame {

    private String[] fNames; //File Names of the data for Schema Analyser. The data format is frame number space x space y space newline. 
                             //x and y co-ordinates are stored as float !!! (Not required and over kill)
    private SchemaDataReader analyst = new SchemaDataReader();

    /**
     * Creates new form FrontEnd_MainFrame
     */
    public FrontEnd_MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar_FrontEnd = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenVideoMenu = new javax.swing.JMenuItem();
        OpenTrackDataMenu = new javax.swing.JMenuItem();
        ImportSchemaAnalyser = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        AnalysisMenu = new javax.swing.JMenu();
        TrackMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MapsMenu = new javax.swing.JMenu();
        GenerateHMaps = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileMenu.setText("File");

        OpenVideoMenu.setText("Open Video");
        OpenVideoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenVideoMenuActionPerformed(evt);
            }
        });
        FileMenu.add(OpenVideoMenu);

        OpenTrackDataMenu.setText("Open Track Data");
        FileMenu.add(OpenTrackDataMenu);

        ImportSchemaAnalyser.setText("Import SchemaAnalyser Positions");
        ImportSchemaAnalyser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportSchemaAnalyserActionPerformed(evt);
            }
        });
        FileMenu.add(ImportSchemaAnalyser);

        jMenuItem1.setText("Export Track Data");
        FileMenu.add(jMenuItem1);

        MenuBar_FrontEnd.add(FileMenu);

        AnalysisMenu.setText("Analysis");
        MenuBar_FrontEnd.add(AnalysisMenu);

        TrackMenu.setText("Track");

        jMenuItem3.setText("Object Settings");
        TrackMenu.add(jMenuItem3);

        jMenuItem2.setText("Start Tracking");
        TrackMenu.add(jMenuItem2);

        MenuBar_FrontEnd.add(TrackMenu);

        MapsMenu.setText("Maps");

        GenerateHMaps.setText("Generate HMaps");
        MapsMenu.add(GenerateHMaps);

        MenuBar_FrontEnd.add(MapsMenu);

        setJMenuBar(MenuBar_FrontEnd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenVideoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenVideoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenVideoMenuActionPerformed

    private void ImportSchemaAnalyserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportSchemaAnalyserActionPerformed
        // TODO add your handling code here:
        MultiSelectFrame Fs = new MultiSelectFrame();
        Fs.setVisible(true);
        
        this.fNames = Fs.getSelectionArray();
        analyst.run();
        
    }//GEN-LAST:event_ImportSchemaAnalyserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontEnd_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontEnd_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontEnd_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontEnd_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontEnd_MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AnalysisMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem GenerateHMaps;
    private javax.swing.JMenuItem ImportSchemaAnalyser;
    private javax.swing.JMenu MapsMenu;
    private javax.swing.JMenuBar MenuBar_FrontEnd;
    private javax.swing.JMenuItem OpenTrackDataMenu;
    private javax.swing.JMenuItem OpenVideoMenu;
    private javax.swing.JMenu TrackMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fNames : fNames is a string array with file Names of the data for Schema Analyser. The data format is frame number space x space y space newline. 
     *                       x and y co-ordinates are stored as float !!! (Not required and over kill)
     */
    public String[] getfNames() {
        return fNames;
    }
}
